### ISSUE TITLE
안녕하세요!! 메세지를 보내고 나서 새로고침을 해야 올라와요

### ISSUE THREAD

**Issue by ethznn** [luciuschoi/chatbox#2]
메세지를 보내고 나서 새로고침을 하지않고 메세지를 계속 보내면 그냥 메세지 리스트가 계속 업데이트가 안되고 새로고침을 한번했을때 한꺼번에 올라옵니다 ㅠㅠ

**Comment by luciuschoi** [comment]
지금 이 저장소의 소스로 테스트해 봤는데, 정상적으로 잘 동작합니다. 콘솔에서 어떤 에러가 발생하는지요?

**Comment by ethznn** [comment]
아 죄송합니다 ㅠㅠ다시 테스트했었을때 예전에 해결했었는데 제가 issue에 말씀을 드리고 close 해야 하는걸 깜빡하고  눌렀다가 네트워크가 왔다갔다 하는 바람에 다시 reopen 이 되었습니다 ㅠㅠ actioncalbe 공부할 때 많은 도움이 되었었습니다. 감사합니다 !!

**Comment by luciuschoi** [comment]
👍
